name: Automatic deployments

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5' # Runs at 11 am UTC, Monday to Friday

jobs:
  deploy:
    name: Deploy
    runs-on: ['self-hosted', 'org']
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Import Secrets from OpenBao
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          # Your OpenBao URL
          url: https://openbao.akeyless.celo-networks-dev.org
          # Authentication configuration
          method: jwt
          path: github
          role: "celo-org_celo-mondo_main"
          # Secrets to retrieve: <PATH> <KEY> | <ENV_VAR_NAME>
          secrets: |
            secrets/data/static-secrets/dev-tooling-circle/vercel/celo-mondo_vercel_deploy_hook value | TOKEN_VAR

      - name: Trigger Deployment
        env:
          DEPLOYMENT_WEBHOOK_URL: ${{ env.TOKEN_VAR }}
        run: |
          curl -s -o /dev/null -X GET "$DEPLOYMENT_WEBHOOK_URL"
